# Generated by Django 4.2.4 on 2023-09-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_5', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CameModel',
            new_name='GameModel',
        ),
    ]
