# Generated by Django 4.2.4 on 2023-09-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_5', '0003_gamermodel_gamelibrarymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameLibraryModel',
            new_name='GamerLibraryModel',
        ),
    ]
